# Generated by Django 5.0.6 on 2024-07-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(max_length=20, verbose_name='PAN Number')),
                ('aadhaar_number', models.CharField(max_length=20, verbose_name='Aadhaar Number')),
            ],
        ),
    ]
