# Generated by Django 5.0.6 on 2024-07-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securedata',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='securedata',
            name='pan_number',
        ),
        migrations.AddField(
            model_name='securedata',
            name='aadhaar_number_encrypted',
            field=models.BinaryField(verbose_name='Encrypted Aadhaar Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securedata',
            name='pan_number_encrypted',
            field=models.BinaryField(verbose_name='Encrypted PAN Number'),
            preserve_default=False,
        ),
    ]
