# Generated by Django 5.0.6 on 2024-07-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_remove_securedata_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedata',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='User ID'),
            preserve_default=False,
        ),
    ]
