# Generated by Django 5.0.6 on 2024-07-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_securedata_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedata',
            name='bank_upi_encrypted',
            field=models.BinaryField(blank=True, null=True, verbose_name='Encrypted UPI id'),
        ),
    ]
