# Generated by Django 5.0.6 on 2024-07-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_securedata_bank_upi_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securedata',
            name='aadhaar_number_encrypted',
            field=models.BinaryField(blank=True, null=True, verbose_name='Encrypted Aadhaar Number'),
        ),
        migrations.AlterField(
            model_name='securedata',
            name='pan_number_encrypted',
            field=models.BinaryField(blank=True, null=True, verbose_name='Encrypted PAN Number'),
        ),
    ]
